databases:
  - name: hellodb
    plan: free
    databaseName: hello_db
    user: hello_user
services:
  - type: web
    plan: free
    name: hello
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn hello.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hellodb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
