# Generated by Django 5.0.6 on 2024-05-11 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_order_options_remove_order_id_order_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
